### ISSUE TITLE
Support volume mounts for @kubernetes

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#1117]
https://outerbounds-community.slack.com/archives/C02116BBNTU/p1660059534420369?thread_ts=1659639983.818119&cid=C02116BBNTU via chat.metaflow.org

**Comment by roofurmston** [comment]
How did you envisage this being implemented @savingoyal ?

I've been through the code base and made a very rough straw man proposal. Would be interested in getting some feedback to see whether or not you think it is reasonable. 

For context, the following is a rough example of how we manage external volumes through Argo Workflows:

```
workflowSpec:
    entrypoint: main
    serviceAccountName: logistics-serviceaccount
    volumeClaimTemplates:
      - metadata:
          name: workflow-storage
        spec:
          storageClassName: efs-sc
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 240Gi

    .......
    templates:
    - name: step1
      image: alpine:latest
      command: [sh, -c]
      args: ["echo hello world > /data/hello_world.txt"]
      volumeMounts:
        - name: workflow-storage
          mountPath: "/data"
``` 

- Add `VolumeClaimTemplates` to the [WorkflowSpec class](https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/argo/argo_workflows.py#L1054).
- The volume claims would are added to the WorkflowTemplate during the [template creation](https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/argo/argo_workflows.py#L292).
- It seems that Metaflow already uses `VolumeMounts` on the step-level in Argo [here](https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/argo/argo_workflows.py#L947). So the suggestion would be that the volume mounts on the step level can be done through the `kubernetes` decorator.

Currently I have considered the following:

- Mechanism to specify the VolumeClaimTemplates on a flow level.
- How the approach would work when running on kubernetes outside of Argo Workflows.

**Comment by shrinandj** [comment]
Does this issue also apply to Argo workflows? Or would it be better to create a separate one for tracking that work?

**Comment by rparundekar** [comment]
@shrinandj , @savingoyal 

I want to use an existing PVC in one step.  This example (from Argo workflows) shows how you can have an intermediate step to create the volume and then use it in the downstream step. Ignoring the creation step and assuming existing PVC, the "specifying the PVC" part looks much easier. 

e.g. `@kubernetes(pvc_mounts = {"pvc-name": "/mnt/vol", ... })` 

WDYT? How would one go about implementing this?

Argo example:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-level-volume-
spec:
  entrypoint: generate-and-use-volume
  templates:
  - name: generate-and-use-volume
    steps:
    - - name: generate-volume
        template: generate-volume
        arguments:
          parameters:
            - name: pvc-size
              # In a real-world example, this could be generated by a previous workflow step.
              value: '1Gi'
    - - name: generate
        template: whalesay
        arguments:
          parameters:
            - name: pvc-name
              value: '{{steps.generate-volume.outputs.parameters.pvc-name}}'
    - - name: print
        template: print-message
        arguments:
          parameters:
            - name: pvc-name
              value: '{{steps.generate-volume.outputs.parameters.pvc-name}}'

  - name: generate-volume
    inputs:
      parameters:
        - name: pvc-size
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          generateName: pvc-example-
        spec:
          accessModes: ['ReadWriteOnce', 'ReadOnlyMany']
          resources:
            requests:
              storage: '{{inputs.parameters.pvc-size}}'
    outputs:
      parameters:
        - name: pvc-name
          valueFrom:
            jsonPath: '{.metadata.name}'

  - name: whalesay
    inputs:
      parameters:
        - name: pvc-name
    volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: '{{inputs.parameters.pvc-name}}'
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["echo generating message in volume; cowsay hello world | tee /mnt/vol/hello_world.txt"]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol

  - name: print-message
    inputs:
        parameters:
          - name: pvc-name
    volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: '{{inputs.parameters.pvc-name}}'
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo getting message from volume; find /mnt/vol; cat /mnt/vol/hello_world.txt"]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
```
