### ISSUE TITLE
AWS Template S3 bucket prefixes might not match defaults in `metaflow configure aws`

### ISSUE THREAD

**Issue by dennismoe** [Netflix/metaflow#2247]
I encountered a small issue. 
The default S3 prefixes in the [AWS Template](https://github.com/outerbounds/metaflow-tools/tree/b76986369a8a44ce6186743c95c7e65143335982/aws/cloudformation) might not match with the suggested S3 prefixes in [`metaflow configure aws`](https://docs.outerbounds.com/engineering/operations/configure-metaflow/)

https://github.com/outerbounds/metaflow-tools/blob/b76986369a8a44ce6186743c95c7e65143335982/aws/cloudformation/metaflow-cfn-template.yml#L1835-L1840

```yaml
  MetaflowDataStoreS3Url:
    Description: Amazon S3 URL for Metaflow DataStore [METAFLOW_DATASTORE_SYSROOT_S3]
    Value: !Sub "s3://${MetaflowS3Bucket}/metaflow"
  MetaflowDataToolsS3Url:
    Description: Amazon S3 URL for Metaflow DataTools [METAFLOW_DATATOOLS_S3ROOT]
    Value: !Sub "s3://${MetaflowS3Bucket}/data"
```

`metaflow configure aws` suggests `metaflow/data` as default prefix for `METAFLOW_DATATOOLS_S3ROOT` if the environment variable `METAFLOW_DATATOOLS_S3ROOT` isn't set already - what should not be assumed in my opinion.

https://github.com/Netflix/metaflow/blob/01e52c51de4338b15e23300b1e9fcbaf0d076073/metaflow/cmd/configure_cmd.py#L262-L265
