### ISSUE TITLE
CloudFormation template has only C4 instances for ECS job queue instance types

### ISSUE THREAD

**Issue by oonisim** [Netflix/metaflow#251]
# Problem

Deployed Metaflow using the CFn template provided. Tried to test GPU with ```@batch(cpu=1, memory=500)``` but Metaflow execution stuck with no progress. 

The Cfn template does not have P instances but only C4 instances specified. 

```
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: !GetAtt 'BatchExecutionRole.Arn'
      ComputeEnvironmentName: !Join [ "-", [ 'batch-compute-env', !Ref 'AWS::StackName' ] ]
      ComputeResources:
        MaxvCpus: !Ref MaxVCPUBatch
        SecurityGroupIds:
          - !Ref SagemakerSecurityGroup
        Type: EC2
        Subnets:
          - !Ref Subnet1
          - !Ref Subnet2
        MinvCpus: !Ref MinVCPUBatch
        InstanceRole: ecsInstanceRole
        InstanceTypes:
          - c4.large
          - c4.xlarge
          - c4.2xlarge
          - c4.4xlarge
          - c4.8xlarge
```

# Question

Please clarify to use GPU, P instance types need to be added in the CFn template.
