### ISSUE TITLE
Debug sporadic 'list index out of range' with AWS Batch

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#507]
Context - https://github.com/Netflix/metaflow-service/issues/7#issuecomment-829715082

https://github.com/Netflix/metaflow-service/issues/7

**Comment by savingoyal** [comment]
Gitter thread - https://gitter.im/metaflow_org/community?at=6088af4bda3e853b33d9096b

**Comment by dpatschke** [comment]
@savingoyal 
I am experiencing the error when running metaflow 2.2.8.

Here is the metadata service information from the CloudFormation template (no changes):
```
Mappings:
  ServiceInfo:
    StackName:
      value: 'metaflow-infrastructure'
    ServiceName:
      value: 'metadata-service-v2'
    ImageUrl:
      value: 'netflixoss/metaflow_metadata_service'
```
I am not sure how to find the exact version of the metadata service. 
If you could share how to find this, I will be happy to provide that detail.

We stood up the infrastructure with the CloudFormation template last October/November and have not updated any components since then.  
If there are components that you feel could benefit from being updated, please share with me how to go about doing this.

We are running Metaflow within our VPC.

My AWS Batch setup is pretty custom with a hard-coded AWS Linux2 AMI that hasn't been updated in a while (February or so). I wonder if I should update this as I have seen 'Old Agent Version' warnings appear within the Batch console.  

If you remember there was [this press release](https://aws.amazon.com/about-aws/whats-new/2020/11/aws-batch-now-has-integrated-amazon-linux-2-support/) from last November but the default image that was being launched via Metaflow was still the Linux1 version well into January of this year. Do you have any idea if this has now actually been fixed by the AWS Batch team?  

I have a SpotFleet attached as well.
```
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: !GetAtt 'BatchExecutionRole.Arn'
      ComputeResources:
        MaxvCpus: !Ref MaxVCPUBatch
        SecurityGroupIds:
          - !Ref VPCDefaultSecurityGroup
        Ec2KeyPair: !Ref BatchEC2KeyPair
        ImageId: ami-0128839b21d19300e
        LaunchTemplate:
          LaunchTemplateName: MetaflowEC2LaunchTemplate
        AllocationStrategy: BEST_FIT
        Type: SPOT
        BidPercentage: 80
        SpotIamFleetRole: !GetAtt 'MetaflowSpotIamFleetRole.Arn'
        Subnets:
          - !Ref Subnet1Id
          - !Ref Subnet2Id
        MinvCpus: !Ref MinVCPUBatch
        InstanceRole: !GetAtt 'ECSInstanceProfile.Arn'
        InstanceTypes:
          - c5
          - r5
        DesiredvCpus: !Ref DesiredVCPUBatch
        Tags: {"Name": "Metaflow Batch"}
      State: ENABLED
```
If there is anything above that throws up red flags or potential issues for you, please let me know.  
Also, please let me know if there are any additional details which I can provide.

Thanks for your help on this!
